#!/usr/bin/env bash

# Author: Santhosh Siva
# Date Created: 03-08-2025

# Description:
# This script returns the current branch name in a git repository.

source "$(dirname "${BASH_SOURCE[0]}")/utils"

set_flags() {
	while [ $# -gt 0 ]; do
		case "$1" in
		-h | --help)
			echo "g-cb - show current branch name"
			echo " "
			echo "g-cb [options]"
			echo " "
			echo "options:"
			echo "-h, --help          show brief help"
			exit 0
			;;
		*)
			echo "${RED}Unknown option:${NC} $1"
			exit 1
			;;
		esac
		shift
	done
}

main() {
	set_flags "$@"
	validate_dependencies git
	print_banner
	print_message "${BLUE}Fetching current branch...${NC}" 1
	current_branch_name=$(git rev-parse --abbrev-ref HEAD)
	if [ -z "$current_branch_name" ]; then
		print_message "${RED}Failed to get current branch.${NC}"
		exit 1
	fi
	echo "$current_branch_name" | indent
	copy_to_clipboard "$current_branch_name" "Current branch name copied to clipboard."
}

main "$@"
exit 0
