#!/usr/bin/env bash

# Author: Santhosh Siva
# Date Created: 03-08-2025

# Description:
# A script to checkout branches, optionally stash changes, and manage git workflow efficiently.

source "$(dirname "${BASH_SOURCE[0]}")/utils"

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

target_branch=
should_force_push=false

set_flags() {
	while [ $# -gt 0 ]; do
		case "$1" in
		-h | --help)
			echo "g-push - push changes to remote branch"
			echo " "
			echo "g-push [options]"
			echo " "
			echo "options:"
			echo "-h, --help                                                             show brief help"
			echo "--target-branch BRANCH, --target-branch=BRANCH, -t=BRANCH, -t BRANCH   specify the target branch"
			echo "--stash-changes                                                        stash changes before proceeding"
			echo "--force                                                                force push changes to the target branch"
			exit 0
			;;
		-t=* | --target-branch=*)
			target_branch="${1#*=}"
			if [ -z "$target_branch" ]; then
				echo "${RED}Error: No target branch specified.$NC"
				exit 1
			fi
			;;
		-t | --target-branch)
			shift
			if [ $# -gt 0 ]; then
				target_branch="$1"
			else
				echo "${RED}Error: No target branch specified.$NC"
				exit 1
			fi
			;;
		-f | --force)
			should_force_push=true
			;;
		esac
		shift
	done
}

main() {
	set_flags "$@"
	validate_dependencies
	print_banner
	if [ -z "$target_branch" ]; then
		push_changes $(fetch_current_branch) $should_force_push 1
		exit 0
	fi
	push_changes "$target_branch" $should_force_push 1
}

main "$@"
exit 0
