#!/usr/bin/env bash

# Author: Santhosh Siva
# Date Created: 03-08-2025

# Description:
# This script returns the current status of the git repository.

source "$(dirname "${BASH_SOURCE[0]}")/utils"

main() {
	validate_dependencies git figlet lolcat
	print_banner
	git status
}

main "$@"
exit 0
